name: Metrics
on:
  # Schedule updates (each hour)
  schedule: [{cron: "0 * * * *"}]
  # Lines below let you run workflow manually and on each commit
  workflow_dispatch:
  push: {branches: ["master", "main"]}
jobs:
  github-metrics:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS_TOKEN }}

          # Options
          user: igor-lirussi
          template: classic
          base: ""
          base_indepth: yes
          config_timezone: Europe/Istanbul
          plugin_code: yes
          plugin_code_days: 30
          plugin_code_lines: 1
          plugin_code_load: 400
          plugin_code_visibility: public
          plugin_people: yes
          plugin_people_limit: 16
          plugin_people_size: 24
          plugin_people_types: followers
